
gpu_id: '0'

# RecBLR architecture flags
bd_lru_only: False
disable_conv1d: False
disable_ffn: False

# RecBLR settings
hidden_size: 64
num_layers: 2
dropout_prob: 0.2
loss_type: 'CE'
expand: 2
d_conv: 4

# dataset settings
dataset: amazon-beauty
MAX_ITEM_LIST_LENGTH: 200    

USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
load_col:
    inter: [user_id, item_id, timestamp]

user_inter_num_interval: "[5,inf)"
item_inter_num_interval: "[5,inf)"

# training settings
epochs: 100
train_batch_size: 2048
learner: adam
learning_rate: 0.001
eval_step: 1
stopping_step: 10
train_neg_sample_args: ~

# evalution settings
metrics: ['Hit', 'NDCG', 'MRR']
valid_metric: NDCG@10
eval_batch_size: 4096
weight_decay: 0.0
topk: [10, 20]
